CREATE TABLE USER 
(Fname VARCHAR(20) NOT NULL,
Minit CHAR(5),
Lname VARCHAR(20) NOT NULL,
Address VARCHAR(50),
Sex CHAR(5), 
PhoneNo Number(15),
Email VARCHAR(20) NOT NULL,
NormalUserFlag CHAR(5),
AdminFlag CHAR(5),
UserID VARCHAR(20) NOT NULL,
PassWord VARCHAR(20) NOT NULL,
PRIMARY KEY (UserID),
UNIQUE(UserID),
FOREIGN KEY (BookID) REFERENCES BOOKS(BookID) ON DELETE SET NULL ON UPDATE CASCADE);

CREATE TABLE BOOKS 
(BookID NUMBER(10) NOT NULL,
BookTitle VARCHAR(20), NOT NULL,
Description VARCHAR(50),
Author VARCHAR(25),
ISBN NUMBER(15) NOT NULL,
Volume NUMBER(10),
Price NUMBER(15) NOT NULL,
DateAdded Date,
BidingEndDate DATE,
DeptID NUMBER(10),
PRIMARY KEY (BookID),
UNIQUE(BookID),
FOREIGN KEY(DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID),
FOREIGN KEY(USERID) REFERENCES DEPARTMENT(USERID) ON DELETE CASCADE ON UPDATE SET NULL);

CREATE TABLE BIDDING_DETAILS(
BidingUser VARCHAR(20), 
Date DATE,
Price NUMBER(10),
BookID NUMBER(10),
UNIQUE(BidingUser),
PRIMARY KEY (BidingUser));

CREATE TABLE BANKING_DETAILS(
BranchName CHAR(20) NOT NULL,
Name VARCHAR(20) NOT NULL,
Account_No VARCHAR(20) NOT NULL,
UserID VARCHAR(20)
UNIQUE(Account_No),
PRIMARY KEY (Account_No)
FOREIGN KEY (UserID) REFERENCES USER(UserID) ON DELETE CASCADE ON UPDATE SET NULL);

CREATE TABLE NOTIFICATION(
NotificationID VARCHAR(20) NOT NULL,
UserID VARCHAR(20),
RECEIVERID VARCHAR(20),
MESSAGE VARCHAR(150),
BookID NUMBER(10),
DatePosted DATE,
UNIQUE(NotificationID)
PRIMARY KEY (NotificationID),
FOREIGN KEY (BookID) REFERENCES BOOKS(BookID) ON DELETE SET NULL ON UPDATE SET NULL);

CREATE TABLE FINALBIDDING(
BookID NUMBER(10) NOT NULL,
SellerID VARCHAR(20),
Price NUMBER(15),
ReceiverID VARCHAR(20),
BidPrice NUMBER(15),
DateBidded	DATE,
MESSAGE VARCHAR(30)
UNIQUE(BookID)
PRIMARY KEY (BookID) 
FOREIGN KEY (BookID) REFERENCES BOOKS(BookID) ON DELETE CASCADE ON UPDATE SET NULL);

CREATE TABLE PAYMENT(
BookID Number(10) NOT NULL,
PayCheckSentDate DATE,
PayCheckReceivedDate DATE,
BookPostedDate DATE,
UpsTrackingNo varchar(15) NOT NULL,
BookReceivedDate DATE,
UNIQUE(UpsTrackingNo)
PRIMARY KEY (UpsTrackingNo)
FOREIGNKEY (BookID) REFERENCES BOOKS(BookID) ON DELETE CASCADE ON UPDATE SET NULL);

CREATE TABLE DEPARTMENT
(Dept_ID NUMBER(10) NOT NULL,
Name VARCHAR(25),
UNIQUE(Dept_ID),
PRIMARY KEY (Dept_ID));

CREATE TABLE RATESERVICE
(BookID NUMBER(10)  NOT NULL,
(SellerID VARCHAR(20), NOT NULL
SellerRating NUMBER(5),
BuyerID VARCHAR(20), NOT NULL 
BuyerRating NUMBER(5),
UNIQUE(BookID)
PRIMARY KEY (BookID),
FOREIGN KEY(BookID) REFERENCES BOOKS(BookID) ON DELETE CASCADE ON UPDATE SET NULL);


VIEW:

/*The user can see the details of other users profile:*/

CREATE VIEW USERDETAILS (Fname,Minit,Lname,No_Of_BooksAdded)
As SELECT Fname,Minit,Lname, Count(*)
FROM USER AS U , BOOKS AS B
WHERE U.UserID = B.UserID AND U.BookID = B.BookID
GROUP U.BY UserID;

/* Users can get notification from other users */
CREATE VIEW USERNOTIFICATION(UserSent, Message, BookID,Date)
As SELECT N.UserID, N.Message,N.BookID, N.DatePosted
	FROM NOTIFICATION AS N, User U
	WHERE N.ReceiverID = U.UserID;

/* Admin can see the list of users using the application */

CREATE VIEW USERLIST AS
SELECT Fname, Minit, Lname 
FROM EMPLOYEE 
WHERE NormalUserFlag = ‘Y’ ;


